### ISSUE TITLE
Feature request - URL validation

### ISSUE THREAD

**Issue by mohdnr** [cds-snc/url-shortener#1]
To enhance security, consider validating that the URL provided isn't an internal resource `127.0.0.1`, `localhost`, etc. A good library to offload this functionality is [Advocate](https://github.com/JordanMilne/Advocate).

My suggestion is to use advocate to request the URL provided by the user and only proceed if `advocate.exceptions.UnacceptableAddressException` is not raised. This will ensure that the URL is safe to store.

**Comment by sylviamclaughlin** [comment]
@mohamed-cds - I have implemented this in the code and will more testing to make sure that it is working as expected. Thank you so much for the suggestion!

**Comment by feralbob** [comment]
I believe that this was mostly addressed by b53cdf2dd2f50b48be31cd055f0d333166136e61 
Can this be marked closed now?
