### ISSUE TITLE
Decide if we want the /docs endpoint exposed

### ISSUE THREAD

**Issue by sylviamclaughlin** [cds-snc/url-shortener#110]
By default FastAPI creates a /docs endpoint where you can view documentation. We need to decide if we want to expose this or and change this in the waf rules.

**Comment by dinophile** [comment]
Can we use it to host the documentation pages?

**Comment by sylviamclaughlin** [comment]
So this is more of a feature that FastAPI has innately build in - essentially, it generates documentation for the endpoints only. Here is some information - https://fastapi.tiangolo.com/features/#:~:text=in%20many%20languages.-,Automatic%20docs,%C2%B6,-Interactive%20API%20documentation
You can't really use it to host the documentation pages - is is more of documenting endpoints and the documentation is automatically generated by FastAPI

**Comment by patheard** [comment]
We chatted about it in the sync yesterday and decided to disable the `/docs` endpoint in Staging/Prod.  I'll leave it available for localhost testing though.

**Comment by patheard** [comment]
Docs endpoint is now only available if a `DOCS_URL` env var exists, which will only be set locally for now.

**Comment by maxneuvians** [comment]
I think we are done with this one in that case 🎉
