### ISSUE TITLE
Implement WET Toolkit

### ISSUE THREAD

**Issue by sylviamclaughlin** [cds-snc/url-shortener#12]
Customize the front end using the Canada Web Experience Toolkit (WET) - https://wet-boew.github.io/wet-boew/index-en.html

**Comment by dinophile** [comment]
@sylviamclaughlin I think we can now use the CDS design system instead maybe?

**Comment by sylviamclaughlin** [comment]
Yes! If we can use the CDS design system, it will be much better.

**Comment by dinophile** [comment]
I'm going to close this then and we can revisit solutioning when we get there!
