### ISSUE TITLE
Front end ADR

### ISSUE THREAD

**Issue by sylviamclaughlin** [cds-snc/url-shortener#13]
Document initial front end plans.

- [ ] Template filled out (Delegating to @jeberhardt but team effort!)
- [ ] Security analysis completed (@ascheid)

List of popular static site generators - https://jamstack.org/generators/

**Comment by dinophile** [comment]
Maybe just a simple nuxt.js or next.js? Depending on our preferred flavour of front end Vue or React!

**Comment by jeberhardt** [comment]
It's worth mentioning that Forms uses **react / next.js**. Probably best if we try and stick with a common tech stack.
