### ISSUE TITLE
Add the forms url to the "Request to have your domain added" link

### ISSUE THREAD

**Issue by sylviamclaughlin** [cds-snc/url-shortener#134]
Make the "Request to have your domain added" link does not work. Add the forms url and any associated logic to make it work.

**Comment by dinophile** [comment]
@sylviamclaughlin do we have the forms on the new...forms for these? (for both English and French)

**Comment by sylviamclaughlin** [comment]
So we do have a forms url that I created a long time ago. It is https://forms-staging.cdssandbox.xyz/id/302
Not sure if you want to update it. If so, I can make the changes and put the forms url into the api so that we can access it.

**Comment by sylviamclaughlin** [comment]
Closing this ticket since Pat is implementing this in the contact us form.
