### ISSUE TITLE
Preload allowed domains at startup

### ISSUE THREAD

**Issue by sylviamclaughlin** [cds-snc/url-shortener#16]
Can we seed the AllowedDomains with some sensible defaults, e.g. Canada.ca or is there another mechanism to preload valid URLS during dev/testing?

**Comment by feralbob** [comment]
I'll look at doing this at the same time as I update the tests for the allowed domains.

Initial thought is to use https://fastapi.tiangolo.com/advanced/events/ and have a simple textfile that is parsed upon startup.
Not sure how easy it is to listen for `SIGNAL` to potentially allow for reloading

**Comment by maxneuvians** [comment]
This is now being loaded from the ENV on start https://github.com/cds-snc/url-shortener/blob/main/api/main.py#L22
