### ISSUE TITLE
Setup AWS Backup for all instances of DynamoDB

### ISSUE THREAD

**Issue by dinophile** [cds-snc/url-shortener#191]
## Summary
In order to satisfy [CP-9 (Contigency Planning - informational system backup).](https://github.com/cds-snc/url-shortener-documentation/issues/171) we would need to set up an AWS Backup instance for our DynamoDB tables OR at least the following parameters must exist on our DynamoDB tables.

**Note** that there are no values specified, and our assumption right now is that the parameters should exist on the resources with some value that we specify?

### Parameters:
```
{
    resourceTags [string]: Any tags for DynamoDB tables for the rule to check, in JSON format,
    resourceId [string]: Name of DynamoDB table for the rule to check,
    crossRegionList [string]: Comma-separated list of destination regions for the cross-region backup copy to be kept,
    crossAccountList [string]: Comma-separated list of destination accounts for cross-account backup copy to be kept,
    maxRetentionDays [int]: The maximum retention period in days for the Backup Vault Lock,
    minRetentionDays [int]: The minimum retention period in days for the Backup Vault Lock,
    backupVaultLockCheck [string]: 'True' or 'False'
}
```
 
### URL Shortener DynamoDB Resources:
- [ ] tfstate table (will be false)
- [ ] tfstate lock table (will be false)
- [ ] url shortener table (should in theory be true if we use AWS Backup)

**Comment by sylviamclaughlin** [comment]
As far as I understand, this should be just setting an AWS Config rule [dynamodb-resources-protected-by-backup-plan](https://docs.aws.amazon.com/config/latest/developerguide/dynamodb-resources-protected-by-backup-plan.html)

**Comment by sylviamclaughlin** [comment]
> 

Honestly, I don't know. But I will look into it more.

**Comment by sylviamclaughlin** [comment]
This has been done.
