### ISSUE TITLE
ATO planning summary (tracking in private repo)

### ISSUE THREAD

**Issue by dinophile** [cds-snc/url-shortener#34]
Epic tracked in private repo here: https://github.com/cds-snc/url-shortener-documentation/issues/3

**Comment by ascheid** [comment]
Reviewed the GC ATO process and decided to follow the profile for Protected B Medium Integrity and Medium Availability. The controls are going to be tracked through Github Issues. Writing the automation that creates issues from the spreadsheet provided so it can be used for future cds' projects.

**Comment by dinophile** [comment]
Closing, as we're now going to track in private repo. Plan is in motion.
