### ISSUE TITLE
Infrastructure ADR

### ISSUE THREAD

**Issue by dinophile** [cds-snc/url-shortener#40]
Document initial infrastructure plans.

- [x] Template filled out (Delegating to @jeberhardt but team effort!)
- [x] Security analysis completed (@ascheid)

**Comment by patheard** [comment]
@dinophile the ADR is now merged in but still in the status of `DRAFT`:
https://github.com/cds-snc/url-shortener/blob/main/adr/2023-01-31-infrastructure-architecture.md

Does the PR we just went through count as the review process and now it's `APPROVED` or is there a different flow you'd like to follow to change the ADR status?

**Comment by patheard** [comment]
ADR is complete and has been reviewed by @ascheid.  Will close this and then we can determine how we want to change the status as a team.
