### ISSUE TITLE
Archiving guidance and responsibilities

### ISSUE THREAD

**Issue by dinophile** [cds-snc/url-shortener#57]

**Comment by victoriawl** [comment]
I reached out to Bob/Sylvia's contact at LAC last week but haven't heard anything yet. So far, I can't find anything directive on retention of URLs/webpages. 

The most relevant info I have found is guidance about [Managing and Archiving Web Content](https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/information-management/managing-archiving-web-content.html) which states:
"Web archiving is an IM best practice that will increase the visibility and usefulness of up-to-date web content, and will improve the long-term sustainability of GC websites."

**Comment by victoriawl** [comment]
I followed up with the contact at LAC but have not received a response. I have not found any new information/directives/policies relating to managing and archiving web content. 

Generally, if what we are doing either maintains status quo or improves the current approach, I don't think there should be any major concern from a policy perspective.
