### ISSUE TITLE
Overload POST / to handle both JSON and FormData

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/url-shortener#83]
Currently we have an endpoint `POST /` that can handle Form data and responds with HTML. We also have `POST /shorten ` that can handle JSON data and responds with JSON. Usually you would only have one API, version scoped, endpoint for JSON and have the HTML component use that internally as well. The alternative, which feels slightly odd, and I am not sure why, is to overload ` POST /` to handle both JSON and FormData based on the content type headers (which is their purpose after all). 

Should FastAPI allow easy overloading of the route, I thinking we can just implement it there. If not, then we should change `POST /shorten ` to `POST /api/v1/` or something like that, especially since we may want to expand API endpoints in the future for stats etc.

**Comment by feralbob** [comment]
I think we should just remove the POST version... that was the intent. It was only around because we were using FastAPI to serve a HTML page. As we pull the frontend out into it's own thing; we won't have to serve HTML and the requests will just be regular fetch calls to the actual API end point.

**Comment by maxneuvians** [comment]
I just tried to overload the method and it is a real pain and I don't want to push against the grain here. Agree we should just rename `/shortener` to something logical like `v1` and call it a day.
