### ISSUE TITLE
Solution for 255 char long URLs

### ISSUE THREAD

**Issue by dinophile** [cds-snc/url-shortener#99]

**Comment by maxneuvians** [comment]
I do not think this an issue with the current DB as I was able to just encode

`https://digital.canada.ca/?U2LbSy0KcKdcdSTfmPsRU6e81JBeqsLeNHm9Vxwr3JtOrKreLpV1xcwEDRxK2xcB1LvbmeQ5Urst5dgeL329yYr910wLE8P1XI87vYwwVdzxELbRpXZDzZVUauHoPgwxnLON9uOgxo23MEjbcvdTBtWHvPv7z2Eptb3j01T4crWNp1duh3VcjD8gWpVZytlkwCt4a4DsBT2XR7aQf1nPjDdoffn7aQdGSjdniS9uNXDeaM3SowGkKvwa9ZlY9tt6
` (284 chars)

to 


`http://127.0.0.1:8000/lhgyRBm5`

I am sure there is going to be theoretical DynamoDB limit (400kb). Assuming we are using UTF-8 and each character is 4 bytes I think we can store 102,400 character URLs.
